# 这是项目的需要改动的所有配置的地址的汇总，需要改哪个中间件的地址，在本文件中修改即可！
nft:
  turbo:
    nacos:
      server:
        url: localhost:8848 # nft.turbo.nacos.server.url - Nacos 的地址+端口号 #首次启动前务必修改成你自己的
    mysql:
      url: jdbc:mysql://localhost:3306/microservices # nft.turbo.mysql.url - MySQL 的地址+数据库配置 #首次启动前务必修改成你自己的
      username: root # nft.turbo.mysql.username - MySQL 的用户名 #首次启动前务必修改成你自己的
      password: asda554562 # nft.turbo.mysql.password - MySQL 的密码 #首次启动前务必修改成你自己的
    redis:
      url: localhost  # nft.turbo.redis.url - Redis 的地址 #首次启动前务必修改成你自己的
      port: 6379  # nft.turbo.redis.port - Redis 的端口号 #首次启动前务必修改成你自己的
      password: ''  # nft.turbo.redis.password - Redis 的密码 #首次启动前务必修改成你自己的
    dubbo:
      nacos:
        namespace: aa1c1c78-52b1-4ea7-b8fb-c50075b2f26d  # nft.turbo.dubbo.nacos.namespace - 自己到nacos上创建一个给dubbo用的namespce，然后和这里保持一致，首次启动前务必修改成你自己的 #首次启动前务必修改成你自己的
        group: dubbo1  # nft.turbo.dubbo.nacos.group - 自己到nacos上创建一个给dubbo用的 group，然后和这里保持一致，首次启动前务必修改成你自己的 #首次启动前务必修改成你自己的
    sentinel:
      url: localhost:8080 # nft.turbo.sentinel.url - Sentinel Dashboard 的地址，首次启动前务必修改成你自己的
