spring:
  cloud:
    gateway:
      # 全局 CORS 配置
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
      # ========== 路由配置 ==========
      # 格式：
      #   id: 服务标识（任意唯一名称）
      #   uri: lb://nacos上的服务名
      #   predicates: 匹配路径
      routes:
        - id: scaffold-auth
          uri: lb://scaffold-auth
          predicates:
            - Path=/auth/**

        - id: scaffold-user
          uri: lb://scaffold-user
          predicates:
            - Path=/user/**

        - id: scaffold-goods
          uri: lb://scaffold-goods
          predicates:
            - Path=/goods/**

        # ===== 新增服务路由模板 =====
        # - id: your-service
        #   uri: lb://your-service-name
        #   predicates:
        #     - Path=/your-api/**

server:
  port: 8081
